const productsData = [
    {
      id: "1",
      url: "images/products/1.jpg",
      resUrl: "../images/products/1res.jpg",
      price: "₹61,990.00",
      value: "61,990",
      accValue: "61990",
      discount: "-46%",
      mrp: "₹1,15,668.00",
      name: "Lenovo ThinkBook 14 Intel Core i5 11th Gen 14 inch (35.56cm) FHD IPS Thin & Light Laptop (16GB RAM/512GB SSD/Windows 11 Home/MS Office 2021/FPR/Intel Iris Xe Graphics Mineral Grey/1.4 kg), 20VDA0TLIH",
      category: "electronics",
      subCategory: "laptop",
      points: [
        "ThinkBook 14 Reliability tested on 12 MIL-STD-810H Methods and 22 Procedures | Body Material: Aluminium | Surface Treatment: Anodizing sandblasting | Built to withstand rugged usage and can handle accidental knocks, drops, and even spills",
        "Processor: 11th Gen Intel Core i5-1135G7, 2.4 Ghz base clock, 4.2 Ghz max boost clock, 4 Cores, 8 MB Cache | Memory: 16GB (8GB soldered + 8GB SO-DIMM) RAM DDR4-3200 MHz upgradable upto 40 GB | Storage: 512GB SSD M.2",
        "Operating System: Preloaded Windows 11 Home with Lifetime Validity | Pre-installed software: Microsoft Office Home & Student 2021",
        "Display: 14-inch (35.56 cm) screen with (1920X1080) Full HD IPS 250 nits Antiglare display | Graphics: Integrated Intel Iris Xe Graphics comes with DirectX 12 enables amazing graphics | Monitor Support: Supports up to 4 independent displays",
        "Ports: 2x USB 3.2 Gen 1 (1x Always On), 1x USB-C 3.2 Gen 2 (support data transfer, PD 3.0 and DP 1.4), 1x Thunderbolt 4 / USB4 40Gbps (support data transfer, PD 3.0 and DP 1.4), 1x HDMI 1.4b, 1x Card reader, 1x Ethernet (RJ-45), 1x Headphone / microphone combo jack (3.5mm)"
      ],
      unitsInStock: 20,
      unitsSold: 7,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "2",
      url: "images/products/2.jpg",
      resUrl: "../images/products/2res.jpg",
      price: "₹39,499.00",
      name: "Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM, 128GB Storage) with No Cost EMI & Additional Exchange Offers",
      category: "electronics",
      subCategory: "mobile",
      resUrl: "../images/products/2res.jpg",
      value: "39,499",
      accValue: "39499",
      discount: "-47%",
      mrp: "₹74,999.00",
      points: [
        "5G Ready powered by Qualcomm Snapdragon 865 Octa-Core processor, 8GB RAM, 128GB internal memory expandable up to 1TB, Android 11.0 operating system and dual SIM",
        "Triple Rear Camera Setup - 12MP (Dual Pixel) OIS F1.8 Wide Rear Camera + 8MP OIS Tele Camera + 12MP Ultra Wide | 30X Space Zoom, Single Take & Night Mode | 32MP F2.2 Front Punch Hole Camera",
        "6.5-inch(16.40 centimeters) Infinity-O Super AMOLED Display with 120Hz Refresh rate, 1080 x 2400 (FHD+) Resolution",
        "4500 mAh battery (Non -removable) with Super Fast Charging, FAst Wireless Charging & Finger Print sensor",
        "IP68 Rated, MicroSD Card Slot (Expandable upto 1 TB), Dual Nano Sim, Hybrid Sim Slot, 5G+5G Dual stand by"
      ],
      unitsInStock: 20,
      unitsSold: 13,
      rating: 3.7,
      reviews: 210,
      carbonFootprint: 2.9,
      ecoScore: 55,
      isEcoFriendly: false,
      groupBuyEligible: true
    },
    {
      id: "3",
      url: "images/products/3.jpg",
      price: "₹21,900.00",
      name: "New Apple AirPods Pro with MagSafe Charging Case",
      category: "electronics",
      subCategory: "earbuds",
      resUrl: "../images/products/3res.jpg",
      value: "21,900",
      accValue: "21900",
      discount: "-12%",
      mrp: "₹24,900.00",
      points: [
        "Active Noise Cancellation blocks outside noise, so you can immerse yourself in music",
        "Transparency mode for hearing and interacting with the world around you",
        "Spatial audio with dynamic head tracking places sound all around you",
        "Adaptive EQ automatically tunes music to your ears",
        "Three sizes of soft, tapered silicone tips for a customisable fit"
      ],
      unitsInStock: 20,
      unitsSold: 2,
      rating: 4.8,
      reviews: 1120,
      carbonFootprint: 0.9,
      ecoScore: 88,
      isEcoFriendly: true,
      groupBuyEligible: true
    },
    {
      id: "4",
      url: "images/products/4.jpg",
      price: "₹1,299.00",
      name: "boAt Airdopes 121v2 True Wireless Earbuds with Upto 14 Hours Playback, Lightweight Earbuds, 8MM Drivers, LED Indicators and Multifunction Controls(Active Black)",
      category: "electronics",
      subCategory: "earbuds",
      resUrl: "../images/products/4res.jpg",
      value: "1,299",
      accValue: "1299",
      discount: "-57%",
      mrp: "₹2,990.00",
      points: [
        "Playback- Airdopes 121v2 offers a nonstop playback of up to 3.5H with each charge and an additional 10.5H playtime with the included charging case",
        "Lightweight- With a dual tone finish on a lightweight ergonomic design weighing just around 4g per earbud, get ready to groove in full flow with Airdopes 121v2v2 TWS earbuds",
        "Drivers- It possesses powerful 8mm drivers that pump out immersive auditory experience all day long",
        "Battery Indicator- Its carry cum charge case also has the battery LED indicator that shows the remaining power for the case",
        "Controls- The true wireless earbuds offer easy access multifunction button controls with stereo calling feature for an overall seamless user experience."
      ],
      unitsInStock: 20,
      unitsSold: 19,
      rating: 3.9,
      reviews: 450,
      carbonFootprint: 3.2,
      ecoScore: 61,
      isEcoFriendly: false,
      groupBuyEligible: false
    },
    {
      id: "5",
      url: "images/products/5.jpg",
      price: "₹999.00",
      name: "Classic Mosquito Net for Double Bed, Embroidery, King Size, Polyester, Strong 30GSM, PVC Coated Steel (L200cm X W200cm X H145cm) Foldable for Double Bed - King Size, Blue",
      category: "home",
      subCategory: "mosquito net",
      resUrl: "../images/products/5res.jpg",
      value: "999",
      accValue: "999",
      discount: "-50%",
      mrp: "₹2,000.00",
      points: [
        "Size of Double bed is 200cm X 200cm X 145cm (i.e. 6.56ft X 6.56ft X 4.75ft) can Easily accommodate bed for King size, Super King size bed. Suitable for 2 Adults & 1 Child.",
        "Easily Washable (steel wires are corrosion resistant), Self-Supporting, No Requirement to nail the wall.",
        "Pops up in an Instant and Automatically, Can be folded in less than 30 Seconds.",
        "Storage Bag Included at free of cost, comes with patches to cover the future accidental holes in the mosquito net, Provided with large Zipper gates on two Sides with inner and outer runner for easy and convenient Entry and Exit.",
        "Easy to fold, Easy to carry, it offers a healthy environment to sleep in."
      ],
      unitsInStock: 20,
      unitsSold: 0,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "6",
      url: "images/products/6.jpg",
      price: "₹2,097.00",
      name: "crocs Unisex-Adult Bayaband Clog",
      category: "fashion",
      subCategory: "clogs",
      resUrl: "../images/products/6res.jpg",
      value: "2,097",
      accValue: "2097",
      discount: "-40%",
      mrp: "₹3,495.00",
      points: [
        "Sole: Ethylene Vinyl Acetate",
        "Sole: Ethylene Vinyl Acetate",
        "Shoe Width: Regular",
        "Outer Material: EVA. Washes off with soap and water",
        "Closure Type: Slip On"
      ],
      unitsInStock: 20,
      unitsSold: 11,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "7",
      url: "images/products/7.jpg",
      price: "₹1,619.00",
      name: "INDO ERA Women's Viscose Embroidered Straight Kurta Palazzo With Dupatta Set",
      category: "fashion",
      subCategory: "kurta",
      resUrl: "../images/products/7res.jpg",
      value: "1,619",
      accValue: "1619",
      discount: "-60%",
      mrp: "₹3,999.00",
      points: [
        "Care Instructions: Dry Clean Only",
        "Fit Type: Regular",
        "Print & Pattern : Solid ; Package Contant : Kurta, Palazzo With Dupatta",
      ],
      unitsInStock: 20,
      unitsSold: 20,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "8",
      url: "images/products/8.jpg",
      price: "₹2,884.00",
      name: "QUBO Smart Cam 360 | 1080p Full HD Wi-Fi Camera | Trust of Hero Group | 360° Deg Coverage with Pan & Tilt | Intruder Alarm | Full Color in Low Light | Two Way Talk | Alexa & OK Google | Made in India",
      category: "electronics",
      subCategory: "camera",
      resUrl: "../images/products/8res.jpg",
      value: "2,884",
      accValue: "2884",
      discount: "-28%",
      mrp: "₹3,990.00",
      points: [
        "PROUDLY INDIAN: Qubo Smart Cam 360 is Designed & Made in INDIA. Engineered for the Security Needs of the Indian Market.",
        "TRUST OF HERO GROUP: Our Round-the-Clock Customer Service & Wide field Network not only resolves your all concerns & queries but rather ensures complete peace of mind for Lifetime.",
        "360 COVERAGE: Multi-Directional rotation of the lens ensures that there are no blind spots. NOTE: Qubo Smart Cam 360 is designed to be used indoors only.",
        "THEFT PROOF CLOUD STORAGE: Secure all your recordings on cloud storage based in India. Your private home moments stay with you even if the device is stolen.",
        "PERSON DETECTION WITH INTRUDER ALARM : Advanced AI capabilities that can smartly detect & notify whenever a person is detected. You can also ring an automatic loud siren in case of an intrusion."
      ],
      unitsInStock: 20,
      unitsSold: 5,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "9",
      url: "images/products/9.jpg",
      price: "₹1,299.00",
      name: "TIMEX Analog Men's Watch",
      category: "fashion",
      subCategory: "watch",
      resUrl: "../images/products/9res.jpg",
      value: "1,299",
      accValue: "1299",
      discount: "-19%",
      mrp: "₹1,595.00",
      points: [
        "Case Shape: Round, Dial Glass Material: Mineral, Band material: Leather",
        "Watch Movement Type: Quartz, Watch Display Type: Analog",
        "Case Material: Brass, Case Diameter: 40 millimeters, Brass Bezel ; Case Thickness: 8.8mm",
        "Water Resistance Depth: 30 meters, Buckle Clasp",
        "Ideal for birthday, anniversary and wedding gift"
      ],
      unitsInStock: 20,
      unitsSold: 16,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "10",
      url: "images/products/10.jpg",
      price: "₹429.00",
      name: "Yogabar Dark Chocolate & Cranberry Muesli 700g - Breakfast Cereal with 83% Nuts & Seeds, Dried Fruits, & Whole Grains - Vegan & Gluten Free Snack",
      category: "beauty",
      subCategory: "muesli",
      resUrl: "../images/products/10res.jpg",
      value: "429",
      accValue: "429",
      discount: "-14%",
      mrp: "₹499.00",
      points: [
        "Whole grains: Quinoa, Oats and Brown Rice",
        "Made from 100% natural ingredients",
        "Rich in nuts and dried fruits: almonds, raisins, dried cranberries rich in seeds: pumpkin, chia and flax",
        "Antioxidant rich dark chocolate + cranberry",
        "Slow-roasted, slow ground in small batches for superior flavour"
      ],
      unitsInStock: 20,
      unitsSold: 3,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "11",
      url: "images/products/11.jpg",
      price: "₹358.00",
      name: "Integriti Men Sweatshirt",
      category: "fashion",
      subCategory: "sweatshirt",
      resUrl: "../images/products/11res.jpg",
      value: "358",
      accValue: "358",
      discount: "-86%",
      mrp: "₹2,499.00",
      points: [
        "Care Instructions: Machine Wash",
        "Fit Type: Modern",
        "Hooded,Long Sleeve,Print",
        "Sweatshirt",
        "Package Dimensions: 10.7 L x 39.6 H x 38.0 W (centimeters)"
      ],
      unitsInStock: 20,
      unitsSold: 10,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "12",
      url: "images/products/12.jpg",
      price: "₹630.00",
      name: "Harpa Synthetic a-line Dress (GR5759_Navy_Small)",
      category: "fashion",
      resUrl: "../images/products/12res.jpg",
      value: "630",
      accValue: "630",
      discount: "-70%",
      mrp: "₹2,099.00",
      points: [
        "Care Instructions: Hand Wash Only",
        "Color name: pink",
        "100% Polyester",
        "Hand wash; A-line",
        "Sleeveless"
      ],
      unitsInStock: 20,
      unitsSold: 15,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "13",
      url: "images/products/13.jpg",
      price: "₹3,999.00",
      name: "boAt Stone 1200 14W Bluetooth Speaker with Upto 9 Hours Battery, RGB LEDs, IPX7 and TWS Feature(Blue)",
      category: "electronics",
      resUrl: "../images/products/13res.jpg",
      value: "3,999",
      accValue: "3999",
      discount: "-43%",
      mrp: "₹6,990.00",
      points: [
        "It delivers a powerful 14W stereo sound for a complete immersive experience.",
        "Stone 1200 provides a battery time of upto 9 hours without its RGB LEDs and upto 7 hours with it(@60% volume) with a charging time of 4 hours.",
        "Carry your splashproof speakers to anywhere with IPX7 splash & water shield leaving behind the tension of water running over",
        "Add a second speaker with our TWS technology and enjoy sound, twice as powerful, Battery Capacity (mAh) - 3600 mAh, Playback Time - 9 hours, Charging Time - 4 hours, Standby Time 360 hours",
        "Its 360-degree ergonomic design makes it ideal to be carried around anywhere you go. It also comes with a carry strap making it very convenient for you to carry it around."
      ],
      unitsInStock: 20,
      unitsSold: 12,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "14",
      price: "₹699.00",
      value: "699",
      accValue: "699",
      discount: "-53%",
      mrp: "₹1,499",
      url: "images/products/14.jpg",
      category: "home",
      subCategory: "bottle",
      resUrl: "../images/products/14res.jpg",
      name: "Interiocrafts Cast Iron Degchi Style Dhoop and Tealight Candle Holder",
      points: [
        "✔ It can be used as a dhoop dani with the lid on and candle holder with votive stand. A perfect item for your pooja mandir.",
        "✔ The chic functionality of this beautiful votive candle and dhoop holder is inimitable.",
        "✔ Rajasthan is famous for its handicrafts and the creativity of the artists can clearly be seen with use of artifacts.",
        "✔ It will not get heated up while use;It is easy to hold for doing 'Dhuni' in your entire house.",
        "✔ It can be used for inserting loban, bakhoor, samarni dhoop incense sticks",
      ],
      unitsInStock: 20,
      unitsSold: 17,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "15",
      price: "₹499.00",
      url: "images/products/15.jpg",
      name: "Urban Born Cast Iron Metal Flower vase for Home Decor and Living Room Vintage Antique Decor (Gold, 15 x 15 x 15 cm)",
      category: "home",
      resUrl: "../images/products/15res.jpg",
      value: "499",
      accValue: "499",
      discount: "-50%",
      mrp: "₹1,000.00",
      points: [
        "This flower vase is made from one Piece of Iron with unique Decorative design.",
        "Item size : HXW : 15 x 15 cm / Finish- Gold",
        "Package contains -1pc Flower vase without Flowers.Good-quality and stylish products.Flowers are for illustration purpose not with Vase.",
        "This flower vase is made from one Piece of Iron with unique Decorative design.",
        "Great for gifting purposes in Diwali, Birthday, Anniversary, Corporate party etc."
      ],
      unitsInStock: 20,
      unitsSold: 18,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "16",
      price: "₹999.00",
      url: "images/products/16.jpg",
      name: "Livpure Smart Solid Window Polyester 5 feet Curtains with tieback( Beige ) Set",
      category: "home",
      resUrl: "../images/products/16res.jpg",
      value: "999",
      accValue: "999",
      discount: "-33%",
      mrp: "₹1,499.00",
      points: [
        "Color: Beige Size: 5 Feet Material: Polyester Package Contents: 2 Window Curtains Attached tiebacks: Yes (Velcro) Window Curtain Dimensions: 152.4 x 132 CM. | 60 x 52 INCH",
        "Blackout: Blocks 95% sunlight from passing through the curtains Noise reduction: Blocks most of the street noise & keeps the inside undisturbed UV protection: Blocks UV rays from sunlight to pass through into your home Temperature insulation: Blocks heat transfer and helps in maintaining the AC efficiency",
        "Unique 3-Weave Technology: Livpure curtains are made using Triple Weave Technology with three layers of fabric strongly interwoven to ensure effective blackout, protection from the UV rays and insulate your home",
        "Hanging Style: These curtains are easy to install and come with high quality eyelet rings Eyelet Rings: Detachable with 1.5 in inner diameter for the curtain to fit nicely Wash Care: Hands & Machine washable after removing the eyelets, Do not bleed color",
        "Product color may slightly vary due to photographic lighting sources or your monitor settings"
      ],
      unitsInStock: 20,
      unitsSold: 9,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "17",
      price: "₹1,399.00",
      url: "images/products/17.jpg",
      name: "NEW LEAF 220 GSM All-Season Printed Super Soft Light Weight Cotton Comforter Set with 1 Bedsheet 2 Pillow Covers (Double, Blue, Orange) -4 Pieces",
      category: "home",
      resUrl: "../images/products/17res.jpg",
      value: "1,399",
      accValue: "1399",
      discount: "-72%",
      mrp: "₹4,999.00",
      points: [
        "The king size quilt set includes - 1pc Bedsheet 1 quilt (100 inch x 90 inch), 2pcs cover ( 18 inch x 28 inch)",
        "New Embroidered artwork makes the quilts much more durable and lightweight rather than the traditional stitching technique.",
        "The cover and filling are made of 100% Microfiber.",
        "The geometric classic pattern is easy to match your bedroom decor, offering you an elegant and classic feeling.",
        "Machine wash cold, gentle cycle, only non-chlorine bleach when needed, tumble dry low, steam if needed, do not iron. No shrinkage, No colour fading and No unravelling after washing."
      ],
      unitsInStock: 20,
      unitsSold: 14,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "18",
      price: "₹329.00",
      url: "images/products/18.jpg",
      name: "Kaameri Bazaar Bronze Color Metal Bird cage Tea Light Holder with Butter Pot tealight Glass for Home Décor",
      category: "home",
      resUrl: "../images/products/18res.jpg",
      value: "329",
      accValue: "329",
      discount: "-63%",
      mrp: "₹899.00",
      points: [
        "This Diwali Light Your home with this beautiful Bird Cage Tealight Holder",
        "This stunning Kaameri Bazaar Tealight Holder makes for a perfect addition to your home.",
        "BENEFITS: They can accent your home or office for the right decor. Perfect for adding a decorative touch to any room's decor",
        "Made from high quality material, Durable and Long lasting",
        "Ideal For: Decoration, Gifting, Diwali Decoration, Christmas Party Decoration, Home Decor, Candle Light Dinner"
      ],
      unitsInStock: 20,
      unitsSold: 8,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "19",
      price: "₹549.00",
      url: "images/products/19.jpg",
      name: "The Vintage Artefacts Donut White, Ceramic Pot and vase Handcrafted, Round Shaped (vase)",
      category: "home",
      resUrl: "../images/products/19res.jpg",
      value: "549",
      accValue: "549",
      discount: "-63%",
      mrp: "₹1,499.00",
      points: [
        "This Diwali Light Your home with this beautiful Bird Cage Tealight Holder",
        "This stunning Kaameri Bazaar Tealight Holder makes for a perfect addition to your home.",
        "BENEFITS: They can accent your home or office for the right decor. Perfect for adding a decorative touch to any room's decor",
        "Made from high quality material, Durable and Long lasting",
        "Ideal For: Decoration, Gifting, Diwali Decoration, Christmas Party Decoration, Home Decor, Candle Light Dinner"
      ],
      unitsInStock: 20,
      unitsSold: 6,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "20",
      price: "₹1,499.00",
      url: "images/products/20.jpg",
      name: "JH Gallery Handcrafted and Emboss Painted Colorful Wood Elephant Shape Garden Table (8 Inches Height, Red)",
      category: "home",
      resUrl: "../images/products/20res.jpg",
      value: "1,499",
      accValue: "1499",
      discount: "-44%",
      mrp: "₹1,499.00",
      points: [
        "JH Gallery Presents Hand crafted Or Hand Painted decorative wooden small Elephant Stool Multicolored which widely used in worldwide to decor balcony, office stool, living room, side table. It is traditional item made up of mango wood and MDF also.",
        "Package Content -One Wooden Elephant Statue Table Cum Stool/Handcrafted with Artistic Painting",
        "Perfect For Decor as Table It's very suitable for gifting as it comes in best packaging as well. Perfect for using end table nightstand, kids step stool, night stand, keeping your planters, as a stand",
        "Care Instruction : table away from warmth , heat and sunshine. Use dry/wet cotton cloth to remove dirt.",
        "100% Handmade :- Handmade by recognized Artisans from JH Gallery Rajasthan, product created under Make in INDIA"
      ],
      unitsInStock: 20,
      unitsSold: 4,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "1001",
      url: "images/products/eco-bottle.jpg",
      resUrl: "../images/products/eco-bottle-res.jpg",
      price: "₹299.00",
      value: "299",
      accValue: "299",
      discount: "-25%",
      mrp: "₹399.00",
      name: "Eco-Friendly Water Bottle (In Stock)",
      category: "home",
      subCategory: "bottle",
      points: [
        "Made from 100% recycled materials",
        "BPA-free and dishwasher safe",
        "Keeps drinks cold for 12 hours"
      ],
      unitsInStock: 20,
      unitsSold: 1,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "1002",
      url: "images/products/eco-bag.jpg",
      resUrl: "../images/products/eco-bag-res.jpg",
      price: "₹149.00",
      value: "149",
      accValue: "149",
      discount: "-10%",
      mrp: "₹165.00",
      name: "Reusable Shopping Bag (Out of Stock)",
      category: "fashion",
      subCategory: "bag",
      points: [
        "Durable and washable",
        "Folds into a compact pouch",
        "Supports up to 20kg weight"
      ],
      unitsInStock: 20,
      unitsSold: 7,
      rating: 4.2,
      reviews: 320,
      carbonFootprint: 1.8,
      ecoScore: 72,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "101",
      url: "images/products/eco-laptop-1.jpg",
      resUrl: "../images/products/eco-laptop-1res.jpg",
      price: "₹69,999.00",
      value: "69,999",
      accValue: "69999",
      discount: "-30%",
      mrp: "₹99,999.00",
      name: "EcoSmart Ultra Laptop (Recycled Aluminum, Solar Powered)",
      category: "electronics",
      subCategory: "laptop",
      points: [
        "Body made from 90% recycled aluminum",
        "Solar charging support for up to 8 hours",
        "Energy Star certified, ultra-low power consumption"
      ],
      unitsInStock: 10,
      unitsSold: 2,
      rating: 4.9,
      reviews: 540,
      carbonFootprint: 0.5,
      ecoScore: 95,
      isEcoFriendly: true,
      groupBuyEligible: true
    },
    {
      id: "102",
      url: "images/products/eco-earbuds-1.jpg",
      resUrl: "../images/products/eco-earbuds-1res.jpg",
      price: "₹2,499.00",
      value: "2,499",
      accValue: "2499",
      discount: "-20%",
      mrp: "₹3,099.00",
      name: "GreenPods True Wireless Earbuds (Biodegradable Case)",
      category: "electronics",
      subCategory: "earbuds",
      points: [
        "Case made from biodegradable materials",
        "Low EMF, energy-efficient Bluetooth 5.2",
        "Eco-friendly packaging"
      ],
      unitsInStock: 15,
      unitsSold: 1,
      rating: 4.7,
      reviews: 210,
      carbonFootprint: 0.7,
      ecoScore: 92,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "103",
      url: "images/products/eco-mobile-1.jpg",
      resUrl: "../images/products/eco-mobile-1res.jpg",
      price: "₹44,999.00",
      value: "44,999",
      accValue: "44999",
      discount: "-15%",
      mrp: "₹52,999.00",
      name: "EcoPhone X (Recycled Plastic, Modular Design)",
      category: "electronics",
      subCategory: "mobile",
      points: [
        "Body made from 80% recycled plastic",
        "Modular design for easy repairs and upgrades",
        "Low power AMOLED display"
      ],
      unitsInStock: 12,
      unitsSold: 3,
      rating: 4.8,
      reviews: 320,
      carbonFootprint: 0.8,
      ecoScore: 90,
      isEcoFriendly: true,
      groupBuyEligible: true
    },
    {
      id: "104",
      url: "images/products/eco-kurta-1.jpg",
      resUrl: "../images/products/eco-kurta-1res.jpg",
      price: "₹1,899.00",
      value: "1,899",
      accValue: "1899",
      discount: "-10%",
      mrp: "₹2,099.00",
      name: "Organic Cotton Kurta (Handwoven, Plant Dyed)",
      category: "fashion",
      subCategory: "kurta",
      points: [
        "100% organic cotton, handwoven",
        "Plant-based dyes, no chemicals",
        "Fair trade certified"
      ],
      unitsInStock: 8,
      unitsSold: 1,
      rating: 4.6,
      reviews: 110,
      carbonFootprint: 0.4,
      ecoScore: 93,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "105",
      url: "images/products/eco-mosquito-net-1.jpg",
      resUrl: "../images/products/eco-mosquito-net-1res.jpg",
      price: "₹1,299.00",
      value: "1,299",
      accValue: "1299",
      discount: "-20%",
      mrp: "₹1,599.00",
      name: "EcoGuard Mosquito Net (Organic Cotton, Plant Dyed)",
      category: "home",
      subCategory: "mosquito net",
      points: [
        "Made from 100% organic cotton",
        "Plant-based, non-toxic dyes",
        "Biodegradable packaging"
      ],
      unitsInStock: 10,
      unitsSold: 1,
      rating: 4.7,
      reviews: 90,
      carbonFootprint: 0.3,
      ecoScore: 94,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "106",
      url: "images/products/eco-clogs-1.jpg",
      resUrl: "../images/products/eco-clogs-1res.jpg",
      price: "₹2,499.00",
      value: "2,499",
      accValue: "2499",
      discount: "-18%",
      mrp: "₹3,049.00",
      name: "GreenStep Clogs (Recycled EVA, Vegan)",
      category: "fashion",
      subCategory: "clogs",
      points: [
        "Made from 80% recycled EVA",
        "Vegan, cruelty-free manufacturing",
        "Eco-friendly dyes"
      ],
      unitsInStock: 12,
      unitsSold: 2,
      rating: 4.8,
      reviews: 120,
      carbonFootprint: 0.6,
      ecoScore: 91,
      isEcoFriendly: true,
      groupBuyEligible: true
    },
    {
      id: "107",
      url: "images/products/eco-watch-1.jpg",
      resUrl: "../images/products/eco-watch-1res.jpg",
      price: "₹2,199.00",
      value: "2,199",
      accValue: "2199",
      discount: "-22%",
      mrp: "₹2,799.00",
      name: "EcoTime Analog Watch (Bamboo, Solar Powered)",
      category: "fashion",
      subCategory: "watch",
      points: [
        "Case and strap made from sustainable bamboo",
        "Solar powered movement",
        "Plastic-free packaging"
      ],
      unitsInStock: 8,
      unitsSold: 1,
      rating: 4.9,
      reviews: 75,
      carbonFootprint: 0.2,
      ecoScore: 97,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "108",
      url: "images/products/eco-bottle-2.jpg",
      resUrl: "../images/products/eco-bottle-2res.jpg",
      price: "₹349.00",
      value: "349",
      accValue: "349",
      discount: "-15%",
      mrp: "₹410.00",
      name: "PureSip Eco Bottle (Glass, Bamboo Lid)",
      category: "home",
      subCategory: "bottle",
      points: [
        "Borosilicate glass, BPA-free",
        "Bamboo lid, compostable",
        "Zero plastic packaging"
      ],
      unitsInStock: 20,
      unitsSold: 3,
      rating: 4.8,
      reviews: 60,
      carbonFootprint: 0.1,
      ecoScore: 98,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "109",
      url: "images/products/eco-bag-2.jpg",
      resUrl: "../images/products/eco-bag-2res.jpg",
      price: "₹199.00",
      value: "199",
      accValue: "199",
      discount: "-12%",
      mrp: "₹225.00",
      name: "GreenCarry Shopping Bag (Jute, Reusable)",
      category: "fashion",
      subCategory: "bag",
      points: [
        "Made from 100% natural jute",
        "Reusable, washable, and compostable",
        "Supports up to 25kg weight"
      ],
      unitsInStock: 25,
      unitsSold: 4,
      rating: 4.7,
      reviews: 85,
      carbonFootprint: 0.2,
      ecoScore: 96,
      isEcoFriendly: true,
      groupBuyEligible: true
    },
    {
      id: "21",
      url: "images/products/21.jpg",
      price: "₹3,499.00",
      name: "EcoVision Smart Cam 2K (Solar, Recycled Plastic)",
      category: "electronics",
      subCategory: "camera",
      resUrl: "../images/products/21res.jpg",
      value: "3,499",
      accValue: "3499",
      discount: "-30%",
      mrp: "₹4,999.00",
      points: [
        "Solar-powered, no wiring needed",
        "Body made from 70% recycled plastic",
        "AI motion detection, cloud storage"
      ],
      unitsInStock: 15,
      unitsSold: 4,
      rating: 4.6,
      reviews: 180,
      carbonFootprint: 0.7,
      ecoScore: 91,
      isEcoFriendly: true,
      groupBuyEligible: true
    },
    {
      id: "22",
      url: "images/products/22.jpg",
      price: "₹2,799.00",
      name: "GreenGrain Muesli (Organic, Vegan, 1kg)",
      category: "beauty",
      subCategory: "muesli",
      resUrl: "../images/products/22res.jpg",
      value: "2,799",
      accValue: "2799",
      discount: "-20%",
      mrp: "₹3,499.00",
      points: [
        "100% organic grains and fruits",
        "No added sugar, vegan",
        "Compostable packaging"
      ],
      unitsInStock: 30,
      unitsSold: 8,
      rating: 4.7,
      reviews: 95,
      carbonFootprint: 0.2,
      ecoScore: 95,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "23",
      url: "images/products/23.jpg",
      price: "₹499.00",
      name: "EarthyWear Organic Sweatshirt",
      category: "fashion",
      subCategory: "sweatshirt",
      resUrl: "../images/products/23res.jpg",
      value: "499",
      accValue: "499",
      discount: "-60%",
      mrp: "₹1,249.00",
      points: [
        "100% organic cotton",
        "Plant-based dyes, unisex",
        "Plastic-free packaging"
      ],
      unitsInStock: 18,
      unitsSold: 6,
      rating: 4.5,
      reviews: 60,
      carbonFootprint: 0.3,
      ecoScore: 94,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "24",
      url: "images/products/24.jpg",
      price: "₹1,299.00",
      name: "EcoChic Summer Dress (Bamboo Fiber)",
      category: "fashion",
      subCategory: "dress",
      resUrl: "../images/products/24res.jpg",
      value: "1,299",
      accValue: "1299",
      discount: "-35%",
      mrp: "₹1,999.00",
      points: [
        "Made from bamboo fiber",
        "Naturally dyed, breathable",
        "Biodegradable packaging"
      ],
      unitsInStock: 12,
      unitsSold: 3,
      rating: 4.8,
      reviews: 45,
      carbonFootprint: 0.2,
      ecoScore: 97,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "25",
      url: "images/products/25.jpg",
      price: "₹4,499.00",
      name: "EcoBeats Bluetooth Speaker (Recycled Wood)",
      category: "electronics",
      subCategory: "speaker",
      resUrl: "../images/products/25res.jpg",
      value: "4,499",
      accValue: "4499",
      discount: "-25%",
      mrp: "₹5,999.00",
      points: [
        "Enclosure made from recycled wood",
        "Low energy Bluetooth 5.3",
        "Solar charging support"
      ],
      unitsInStock: 10,
      unitsSold: 2,
      rating: 4.7,
      reviews: 70,
      carbonFootprint: 0.4,
      ecoScore: 93,
      isEcoFriendly: true,
      groupBuyEligible: true
    },
    {
      id: "26",
      url: "images/products/26.jpg",
      price: "₹1,199.00",
      name: "GreenCurtain Eco Window Curtain (Organic Cotton)",
      category: "home",
      subCategory: "curtain",
      resUrl: "../images/products/26res.jpg",
      value: "1,199",
      accValue: "1199",
      discount: "-20%",
      mrp: "₹1,499.00",
      points: [
        "100% organic cotton",
        "Plant-based dyes, blocks 90% sunlight",
        "Compostable packaging"
      ],
      unitsInStock: 14,
      unitsSold: 5,
      rating: 4.6,
      reviews: 40,
      carbonFootprint: 0.2,
      ecoScore: 95,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "27",
      url: "images/products/27.jpg",
      price: "₹2,199.00",
      name: "EcoComfort All-Season Comforter (Bamboo Fill)",
      category: "home",
      subCategory: "comforter",
      resUrl: "../images/products/27res.jpg",
      value: "2,199",
      accValue: "2199",
      discount: "-27%",
      mrp: "₹2,999.00",
      points: [
        "Filling made from bamboo fiber",
        "Cover: organic cotton, hypoallergenic",
        "Biodegradable packaging"
      ],
      unitsInStock: 11,
      unitsSold: 2,
      rating: 4.7,
      reviews: 35,
      carbonFootprint: 0.3,
      ecoScore: 96,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "28",
      url: "images/products/28.jpg",
      price: "₹2,499.00",
      name: "GreenTable Mini (Bamboo, Foldable)",
      category: "home",
      subCategory: "table",
      resUrl: "../images/products/28res.jpg",
      value: "2,499",
      accValue: "2499",
      discount: "-15%",
      mrp: "₹2,999.00",
      points: [
        "Made from 100% bamboo",
        "Foldable, lightweight",
        "No plastic parts"
      ],
      unitsInStock: 7,
      unitsSold: 1,
      rating: 4.8,
      reviews: 22,
      carbonFootprint: 0.2,
      ecoScore: 97,
      isEcoFriendly: true,
      groupBuyEligible: false
    },
    {
      id: "29",
      url: "images/products/29.jpg",
      price: "₹799.00",
      name: "EcoVase (Recycled Glass)",
      category: "home",
      subCategory: "vase",
      resUrl: "../images/products/29res.jpg",
      value: "799",
      accValue: "799",
      discount: "-20%",
      mrp: "₹999.00",
      points: [
        "Made from 100% recycled glass",
        "Handcrafted, unique design",
        "Plastic-free packaging"
      ],
      unitsInStock: 10,
      unitsSold: 2,
      rating: 4.7,
      reviews: 30,
      carbonFootprint: 0.1,
      ecoScore: 98,
      isEcoFriendly: true,
      groupBuyEligible: false
    }
  ]
  
  const normalizedProductsData = productsData.map(product => ({
    ...product,
    resUrl: product.resUrl || '',
    price: product.price || '₹0',
    value: product.value || '0',
    accValue: typeof product.accValue === 'string' ? Number(product.accValue.replace(/[^0-9.]/g, '')) : (product.accValue ?? 0),
    discount: product.discount || '',
    mrp: product.mrp || '',
    name: product.name || '',
    category: product.category || 'General',
    subCategory: product.subCategory || '',
    points: Array.isArray(product.points) ? product.points : [],
    rating: typeof product.rating === 'number' ? product.rating : 4,
    reviews: typeof product.reviews === 'number' ? product.reviews : 100,
    carbonFootprint: typeof product.carbonFootprint === 'number' ? product.carbonFootprint : 2.5,
    ecoScore: typeof product.ecoScore === 'number' ? product.ecoScore : 50,
    isEcoFriendly: typeof product.isEcoFriendly === 'boolean' ? product.isEcoFriendly : true,
    groupBuyEligible: typeof product.groupBuyEligible === 'boolean' ? product.groupBuyEligible : false,
    unitsInStock: typeof product.unitsInStock === 'number' ? product.unitsInStock : 0,
    unitsSold: typeof product.unitsSold === 'number' ? product.unitsSold : 0,
  }));

  module.exports = normalizedProductsData;